In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_diabetes

In [6]:
X , y = load_diabetes(return_X_y=True , as_frame=True)


In [ ]:
lr = LinearRegression()

### cross_val_score

In [17]:

score = cross_val_score(lr , X , y , cv=5)
print(score)


[0.42955615 0.52259939 0.48268054 0.42649776 0.55024834]


### cross_validate

In [85]:
from sklearn.model_selection import cross_validate

cv_results = cross_validate(
    lr , X , y ,
    cv=ShuffleSplit(n_splits=5 , test_size=0.2 , random_state=42),
    scoring = "neg_mean_absolute_error",
    return_train_score=True,
    return_estimator=True
)

print(cv_results["fit_time"])
print(cv_results["score_time"])
print(cv_results["test_score"])
print(cv_results["train_score"])
print(cv_results["estimator"])

[0.00199842 0.00099969 0.00100088 0.00100088 0.00100017]
[0.0010016  0.00099993 0.00099874 0.00099921 0.00099921]
[-42.79409468 -41.02966715 -43.71417907 -48.214139   -45.68240405]
[-43.48350352 -43.90847346 -43.40515711 -42.10326561 -42.7099285 ]
[LinearRegression(), LinearRegression(), LinearRegression(), LinearRegression(), LinearRegression()]


#### Kfold

In [14]:
from sklearn.model_selection import KFold

kfold_cv = KFold(n_splits = 5)

score_kfold = cross_val_score(
    lr , X , y , cv = kfold_cv
)
score_kfold

array([0.42955615, 0.52259939, 0.48268054, 0.42649776, 0.55024834])

#### LeaveOneOut

In [29]:
from sklearn.model_selection import LeaveOneOut

loo_cv = LeaveOneOut()

score_loo = cross_val_score(
    lr , X , y , cv = loo_cv,
    scoring = "neg_mean_squared_error"
)
score.mean()

np.float64(3001.7528469994304)

#### ShuffleSplit

In [39]:
from sklearn.model_selection import ShuffleSplit

shuffle_split = ShuffleSplit(n_splits=5, test_size=0.2 ,random_state=42)

score_shuffle_split = cross_val_score(lr , X , y , cv=shuffle_split)
score_shuffle_split.max()

np.float64(0.6083610957824863)