In [8]:
from sklearn.model_selection import StratifiedShuffleSplit
import pandas as pd

data_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'
df = pd.read_csv(data_url , sep=";")

features = df.drop("quality",axis=1)
label = df["quality"]

split = StratifiedShuffleSplit(n_splits=1 , test_size=0.2 , random_state=42) # Define karta hai ki data ko kaise split karna hai !!

for train_index , test_index in split.split(features,label):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

wine_features = strat_train_set.drop("quality" , axis=1)
wine_label = strat_train_set["quality"].copy()

OrdinalEncoder 
- if order matters like-> best > good > bad

In [14]:
from sklearn.preprocessing import OrdinalEncoder

ordinal_encoder = OrdinalEncoder()

ordinalEncoder_result = ordinal_encoder.fit_transform(wine_features)

print(ordinalEncoder_result)

[[ 20. 105.   2. ...  40.  17.  29.]
 [ 22.  60.  33. ...  32.  17.  11.]
 [ 72.  48.  50. ...  22.  39.  28.]
 ...
 [ 31.  32.  32. ...  41.  25.  23.]
 [ 65.  40.  73. ...  32.  23.  35.]
 [ 40.  31.  45. ...  43.  38.  44.]]


One Hot Encoding
- when order doesn't matters like -> city , color , gender
- it returns scipy sparse matrix rather then numpy array

In [15]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()

OneHotEncoder_result = cat_encoder.fit_transform(wine_features)
print(OneHotEncoder_result)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14069 stored elements and shape (1279, 1367)>
  Coords	Values
  (0, 20)	1.0
  (0, 201)	1.0
  (0, 234)	1.0
  (0, 320)	1.0
  (0, 418)	1.0
  (0, 562)	1.0
  (0, 622)	1.0
  (0, 823)	1.0
  (0, 1164)	1.0
  (0, 1227)	1.0
  (0, 1333)	1.0
  (1, 22)	1.0
  (1, 156)	1.0
  (1, 265)	1.0
  (1, 375)	1.0
  (1, 507)	1.0
  (1, 588)	1.0
  (1, 697)	1.0
  (1, 1047)	1.0
  (1, 1156)	1.0
  (1, 1227)	1.0
  (1, 1315)	1.0
  (2, 72)	1.0
  (2, 144)	1.0
  (2, 282)	1.0
  :	:
  (1276, 1165)	1.0
  (1276, 1235)	1.0
  (1276, 1327)	1.0
  (1277, 65)	1.0
  (1277, 136)	1.0
  (1277, 305)	1.0
  (1277, 361)	1.0
  (1277, 454)	1.0
  (1277, 537)	1.0
  (1277, 601)	1.0
  (1277, 1095)	1.0
  (1277, 1156)	1.0
  (1277, 1233)	1.0
  (1277, 1339)	1.0
  (1278, 40)	1.0
  (1278, 127)	1.0
  (1278, 277)	1.0
  (1278, 329)	1.0
  (1278, 426)	1.0
  (1278, 565)	1.0
  (1278, 643)	1.0
  (1278, 930)	1.0
  (1278, 1167)	1.0
  (1278, 1248)	1.0
  (1278, 1348)	1.0
