In [3]:
import numpy as np

In [4]:
# Zeros Array
zero_array=np.zeros((3,3))
print(zero_array)

print()

# ones Array
one_array=np.ones((2,3))
print(one_array)

print()

#np.full( (shape) , number ) :- when we want an espicific number in array.
full_array=np.full( (5,6) , 7 )
print(full_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]


- 1D_Array

In [2]:
arr_1d=np.array([1,2,3,4,5,6])
print(arr_1d)

[1 2 3 4 5 6]


- 2D_Array

In [6]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


- Multi_Dimenstional Array