### Numeric Transformers
* Feature Scaling
* Polynomial Transformation
* Discretization

#### Feature Scaling
* Numerical fetures with different scales lead to slower convergence of iteritave optmization procedures
* it is good practice to scale numerical features so that all of them are on same scale

##### (a) ScandardScaler (b) MaxAbsScaler (c) MinMaxScaler

In [30]:
import pandas as pd
X = pd.DataFrame([4,3,2,5,6])

#### (a) StandardScaler
* Ye data ko mean = 0 aur standard deviation = 1 par scale karta hai.

$$z = \frac{x - \mu}{\sigma}$$

In [31]:
# StandardScaler
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit_transform(X)


array([[ 0.        ],
       [-0.70710678],
       [-1.41421356],
       [ 0.70710678],
       [ 1.41421356]])

#### (b) MinMaxScaler
* Ye data ko strictly ek fixed range (by default 0 se 1) ke beech le aata hai.
$$x_{scaled} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [32]:
from sklearn.preprocessing import MinMaxScaler

MinMaxScaler = MinMaxScaler()
MinMaxScaler.fit_transform(X)

array([[0.5 ],
       [0.25],
       [0.  ],
       [0.75],
       [1.  ]])

#### (c) MaxAbsScaler Formula
Ye data ko uski maximum absolute value se divide karta hai ([-1, 1] range). Isme zeros change nahi hote.

$$x_{scaled} = \frac{x}{\max(|x|)}$$

* **max(|x|)**: Data me sabse badi value (chahe positive ho ya negative, uska absolute number

In [33]:
from sklearn.preprocessing import MaxAbsScaler
mas = MaxAbsScaler()
mas.fit_transform(X)

array([[0.66666667],
       [0.5       ],
       [0.33333333],
       [0.83333333],
       [1.        ]])

#### 4. RobustScaler Formula
Ye mean/max ki jagah Median aur IQR use karta hai, jisse Outliers ka asar nahi padta.

$$x_{scaled} = \frac{x - \text{median}}{IQR}$$

* **median**: Data ki beech ki value (50th Percentile / $Q_2$)
* **IQR**: Interquartile Range (75th Percentile - 25th Percentile / $Q_3 - Q_1$)

In [34]:
from sklearn.preprocessing import RobustScaler

# Scaler banaya
scaler = RobustScaler()

# Data ko fit aur transform kiya
scaler.fit_transform(X)

array([[ 0. ],
       [-0.5],
       [-1. ],
       [ 0.5],
       [ 1. ]])

### Functional Transformer

In [35]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

ft = FunctionTransformer(np.log2)
ft.fit_transform(X)

,0
0,2.000000
1,1.584963
2,1.000000
3,2.321928
4,2.584963


### Polynomial Transformation

In [36]:
from sklearn.preprocessing import PolynomialFeatures

data = {
    'Length': [10, 15, 20, 25, 30],
    'Width':  [5,   8,  10, 12, 15]
}
df = pd.DataFrame(data)

print("--- Original Pandas DataFrame ---")
print(df)
print("\n")

# 2. PolynomialFeatures initialize kiya (degree=2)
# include_bias=False kiya hai taaki extra '1' wala column na aaye
poly = PolynomialFeatures(degree=2, include_bias=False)

# 3. Data ko fit aur transform kiya (ye Numpy array return karta hai)
poly_array = poly.fit_transform(df)

# 4.Scikit-learn se naye columns ke naam maange!
new_columns = poly.get_feature_names_out(df.columns)

# 5. Output ko wapas ek naye Pandas DataFrame me daal diya taaki table achhi dikhe
df_poly = pd.DataFrame(poly_array, columns=new_columns)

print("--- Polynomial Features ke baad Naya DataFrame ---")
print(df_poly)

--- Original Pandas DataFrame ---
   Length  Width
0      10      5
1      15      8
2      20     10
3      25     12
4      30     15


--- Polynomial Features ke baad Naya DataFrame ---
   Length  Width  Length^2  Length Width  Width^2
0    10.0    5.0     100.0          50.0     25.0
1    15.0    8.0     225.0         120.0     64.0
2    20.0   10.0     400.0         200.0    100.0
3    25.0   12.0     625.0         300.0    144.0
4    30.0   15.0     900.0         450.0    225.0


### KBinDiscretizer
* Divides A countinus Variable into bins
* One-Hot-Encoding or Ordinal Encoding is further applied to the bin labels

In [40]:
from sklearn.preprocessing import KBinsDiscretizer

d = [0,0.125,0.25,0.375,0.5,0.675,0.75,0.875,1.0]
df = pd.DataFrame(d)

kbd = KBinsDiscretizer(
    n_bins=5,
    strategy="uniform",
    encode="ordinal"
)
kbd.fit_transform(df)


array([[0.],
       [0.],
       [1.],
       [1.],
       [2.],
       [3.],
       [3.],
       [4.],
       [4.]])